export const currencies: Record<string, string> = {
  "USD": "United States Dollar",
  "$": "United States Dollar", 
  "EUR": "Euro",
  "€": "Euro",
  "JPY": "Japanese Yen",
  "¥": "Japanese Yen",
  "GBP": "British Pound Sterling",
  "£": "British Pound Sterling",
  "AUD": "Australian Dollar",
  "CAD": "Canadian Dollar",
  "CHF": "Swiss Franc",
  "CNY": "Chinese Yuan Renminbi",
  "CN¥": "Chinese Yuan Renminbi",
  "HKD": "Hong Kong Dollar",
  "NZD": "New Zealand Dollar",
  "SEK": "Swedish Krona",
  "KRW": "South Korean Won",
  "₩": "South Korean Won",
  "SGD": "Singapore Dollar",
  "NOK": "Norwegian Krone",
  "MXN": "Mexican Peso",
  "MX$": "Mexican Peso",
  "INR": "Indian Rupee",
  "₹": "Indian Rupee",
  "RUB": "Russian Ruble",
  "₽": "Russian Ruble",
  "ZAR": "South African Rand",
  "R": "South African Rand",
  "TRY": "Turkish Lira",
  "₺": "Turkish Lira",
  "BRL": "Brazilian Real",
  "R$": "Brazilian Real",
  "TWD": "New Taiwan Dollar",
  "NT$": "New Taiwan Dollar",
  "DKK": "Danish Krone",
  "PLN": "Polish Zloty",
  "zł": "Polish Zloty",
  "THB": "Thai Baht",
  "฿": "Thai Baht",
  "IDR": "Indonesian Rupiah",
  "Rp": "Indonesian Rupiah",
  "HUF": "Hungarian Forint",
  "Ft": "Hungarian Forint",
  "CZK": "Czech Koruna",
  "Kč": "Czech Koruna",
  "ILS": "Israeli New Shekel",
  "₪": "Israeli New Shekel",
  "CLP": "Chilean Peso",
  "PHP": "Philippine Peso",
  "₱": "Philippine Peso",
  "AED": "UAE Dirham",
  "د.إ": "UAE Dirham",
  "COP": "Colombian Peso",
  "SAR": "Saudi Riyal",
  "﷼": "Saudi Riyal",
  "MYR": "Malaysian Ringgit",
  "RM": "Malaysian Ringgit",
  "RON": "Romanian Leu",
  "ARS": "Argentine Peso",
  "PEN": "Peruvian Sol",
  "PKR": "Pakistani Rupee",
  "₨": "Pakistani Rupee",
  "VND": "Vietnamese Dong",
  "₫": "Vietnamese Dong",
  "EGP": "Egyptian Pound",
  "NGN": "Nigerian Naira",
  "₦": "Nigerian Naira",
  "BDT": "Bangladeshi Taka",
  "৳": "Bangladeshi Taka",
  "KWD": "Kuwaiti Dinar",
  "QAR": "Qatari Riyal",
  "BHD": "Bahraini Dinar",
  "OMR": "Omani Rial",
  "MAD": "Moroccan Dirham",
  "KES": "Kenyan Shilling",
  "TZS": "Tanzanian Shilling",
  "UGX": "Ugandan Shilling",
  "GHS": "Ghanaian Cedi",
  "₵": "Ghanaian Cedi",
  "UAH": "Ukrainian Hryvnia",
  "₴": "Ukrainian Hryvnia",
  "BGN": "Bulgarian Lev",
  "HRK": "Croatian Kuna",
  "ISK": "Icelandic Krona",
  "LKR": "Sri Lankan Rupee",
  "MMK": "Myanmar Kyat",
  "MNT": "Mongolian Tugrik",
  "₮": "Mongolian Tugrik",
  "NPR": "Nepalese Rupee",
  "MOP": "Macanese Pataca",
  "FJD": "Fijian Dollar",
  "PGK": "Papua New Guinean Kina",
  "TOP": "Tongan Paʻanga",
  "WST": "Samoan Tala",
  "SBD": "Solomon Islands Dollar",
  "BND": "Brunei Dollar",
  "KYD": "Cayman Islands Dollar",
  "JMD": "Jamaican Dollar",
  "TTD": "Trinidad and Tobago Dollar",
  "BSD": "Bahamian Dollar",
  "BBD": "Barbadian Dollar",
  "HTG": "Haitian Gourde",
  "DOP": "Dominican Peso",
  "CRC": "Costa Rican Colón",
  "₡": "Costa Rican Colón",
  "GTQ": "Guatemalan Quetzal",
  "HNL": "Honduran Lempira",
  "NIO": "Nicaraguan Córdoba",
  "PYG": "Paraguayan Guaraní",
  "₲": "Paraguayan Guaraní",
  "UYU": "Uruguayan Peso",
  "BOB": "Bolivian Boliviano",
  "SRD": "Surinamese Dollar",
  "GYD": "Guyanese Dollar",
  "LRD": "Liberian Dollar",
  "SLL": "Sierra Leonean Leone",
  "ETB": "Ethiopian Birr",
  "ZMW": "Zambian Kwacha",
  "MWK": "Malawian Kwacha",
  "MZN": "Mozambican Metical",
  "AOA": "Angolan Kwanza",
  "CDF": "Congolese Franc",
  "XAF": "Central African CFA Franc",
  "XOF": "West African CFA Franc",
  "XPF": "CFP Franc",
  "XCD": "East Caribbean Dollar",
  "MVR": "Maldivian Rufiyaa",
  "SCR": "Seychellois Rupee",
  "MUR": "Mauritian Rupee",
  "KZT": "Kazakhstani Tenge",
  "₸": "Kazakhstani Tenge",
  "UZS": "Uzbekistani Som",
  "TMT": "Turkmenistani Manat",
  "AZN": "Azerbaijani Manat",
  "₼": "Azerbaijani Manat",
  "GEL": "Georgian Lari",
  "₾": "Georgian Lari",
  "AMD": "Armenian Dram",
  "֏": "Armenian Dram",
  "BYN": "Belarusian Ruble",
  "RSD": "Serbian Dinar",
  "MKD": "Macedonian Denar",
  "ALL": "Albanian Lek",
  "L": "Albanian Lek",
  "MDL": "Moldovan Leu",
  "LAK": "Lao Kip",
  "₭": "Lao Kip",
  "KHR": "Cambodian Riel",
  "៛": "Cambodian Riel",
};
